version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=home
      - POSTGRES_PASSWORD=home
      - POSTGRES_DB=home
    ports:
      - "5432:5432"