name: Django CI Pipeline

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install flake8
        flake8 .

  test:
    runs-on: ubuntu-latest
    needs: lint

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env

    - name: Install Docker Compose  # Шаг установки docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d postgres redis
        docker-compose -f docker-compose.yml run web python manage.py test

    - name: Stop services
      run: docker-compose -f docker-compose.yml down  # Останавливаем контейнеры
